//! Names for common evdev key and button codes, for readable probe output only.

pub fn key_name(code: u32) -> Option<&'static str> {
    Some(match code {
        1 => "ESC",
        2 => "1",
        3 => "2",
        4 => "3",
        5 => "4",
        6 => "5",
        7 => "6",
        8 => "7",
        9 => "8",
        10 => "9",
        11 => "0",
        14 => "BACKSPACE",
        15 => "TAB",
        16 => "Q",
        17 => "W",
        18 => "E",
        19 => "R",
        20 => "T",
        21 => "Y",
        22 => "U",
        23 => "I",
        24 => "O",
        25 => "P",
        28 => "ENTER",
        29 => "LEFTCTRL",
        30 => "A",
        31 => "S",
        32 => "D",
        33 => "F",
        34 => "G",
        35 => "H",
        36 => "J",
        37 => "K",
        38 => "L",
        42 => "LEFTSHIFT",
        44 => "Z",
        45 => "X",
        46 => "C",
        47 => "V",
        48 => "B",
        49 => "N",
        50 => "M",
        54 => "RIGHTSHIFT",
        56 => "LEFTALT",
        57 => "SPACE",
        58 => "CAPSLOCK",
        59..=68 => return Some(["F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10"][(code - 59) as usize]),
        69 => "NUMLOCK",
        97 => "RIGHTCTRL",
        100 => "RIGHTALT",
        102 => "HOME",
        103 => "UP",
        104 => "PAGEUP",
        105 => "LEFT",
        106 => "RIGHT",
        107 => "END",
        108 => "DOWN",
        109 => "PAGEDOWN",
        111 => "DELETE",
        125 => "LEFTMETA",
        126 => "RIGHTMETA",
        272 => "BTN_LEFT",
        273 => "BTN_RIGHT",
        274 => "BTN_MIDDLE",
        275 => "BTN_SIDE",
        276 => "BTN_EXTRA",
        _ => return None,
    })
}

pub fn describe(code: u32) -> String {
    match key_name(code) {
        Some(name) => format!("{code} ({name})"),
        None => code.to_string(),
    }
}
